# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3anrdnRVRsoxim5LBvzK9ypxCInt4Li
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')

import pandas as pd

data = pd.read_csv("IMDB Dataset.csv", quoting=3, encoding='utf-8', on_bad_lines='skip')
data.head()

import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return ' '.join(words)

data['review'] = data['review'].astype(str)
data['clean_review'] = data['review'].apply(preprocess_text)

tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(data['clean_review']).toarray()
y = data['sentiment'].apply(lambda x: 1 if x == 'positive' else 0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))

print("\nLogistic Regression Report:\n", classification_report(y_test, y_pred_lr))
print("\nNaive Bayes Report:\n", classification_report(y_test, y_pred_nb))

sns.heatmap(confusion_matrix(y_test, y_pred_lr), annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

from wordcloud import WordCloud

positive_text = ' '.join(data[data['sentiment']=='positive']['clean_review'])
negative_text = ' '.join(data[data['sentiment']=='negative']['clean_review'])

plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.title("Positive Reviews WordCloud")
plt.imshow(WordCloud(max_words=100, background_color='white', colormap='Blues').generate(positive_text))
plt.axis('off')

plt.subplot(1,2,2)
plt.title("Negative Reviews WordCloud")
plt.imshow(WordCloud(max_words=100, background_color='white', colormap='Reds').generate(negative_text))
plt.axis('off')
plt.show()

import pickle

pickle.dump(lr, open("sentiment_model.pkl", "wb"))
pickle.dump(tfidf, open("vectorizer.pkl", "wb"))